### ISSUE TITLE
yo haider i got zucced

### ISSUE THREAD

**Issue by aminozuur** [aminozuur/wordo#12]
I can't reply to your msg on Facebook as i got banned for another 3 days 😠 😜.  I suggest Telegram Messenger, my username is @aminozuur.

**Comment by candh** [comment]
ohhhh shiddddddd i get it. fuck the zucc tho. Anways, it was facebook messenger related thing like I wanted to test. Like I needed two or more people. But you can't use facebook's chat feature I guess? So yeah, nevermind! lol

**Comment by candh** [comment]
amazing way to use github issues tho!

**Comment by aminozuur** [comment]
yeah I can't reply to chat. I can't do anything during the ban except see other people's post.
I'll be glad to test ur shit when the ban is lifted.
