### ISSUE TITLE
Broken profile pictures

### ISSUE THREAD

**Issue by aminozuur** [aminozuur/wordo#2]
Whenever someone updates their profile picture on Twitter, the new picture does not show up on Wordo until that user logs out, and back in to Wordo.

**It should auto-update.**

![screen shot 2016-12-04 at 04 49 11](https://cloud.githubusercontent.com/assets/3943492/20863931/3a742a7a-b9dd-11e6-9dcf-b4a82b88c46d.png)

**Comment by candh** [comment]
Here's what I think: 
I don't think it would be auto updated unless you explicitly make a call for user info every time their profile picture is showed on the screen. This is **not** a good idea.

I think the site should cache it and display the old profile picture (And not completely remove it) and when the user logs backs in, it should replace the data with the new one.

**Comment by aminozuur** [comment]
As a temporary fix, we can add the following line to images, to make it show a sad-emoji instead of the broken-image

`onerror="this.src='/assets/images/broken.png';"`

**Comment by candh** [comment]
WELL I GUESS A SAD PICTURE'S BETTER THAN NO PICTURE

<blockquote class='rg_standalone_container' data-src='//genius.com/annotations/8665919/standalone_embed'><a href='http://genius.com/8665919/Kanye-west-30-hours/I-used-the-western-union-for-you-like-its-no-prob-cause-you-was-in-college-complainin-about-its-no-jobs-but-you-were-suckin-a-nigga-dick-the-whole-time-well-i-guess-a-blowjobs-better-than-no-job'> Well I guess a blowjob&#39;s better than no job</a><br><a href='http://genius.com/Kanye-west-30-hours-lyrics'>&#8213; Kanye West – 30 Hours</a></blockquote>
