### ISSUE TITLE
Timestamp fix "about an hour ago"

### ISSUE THREAD

**Issue by aminozuur** [aminozuur/wordo#4]
Like or comment on a word, and it will say you liked it "about an hour ago". It might have to do with winter-time or something, since it worked fine until a couple weeks ago.

**Comment by candh** [comment]
Seems like you're storing time in the database using that Auto timestamp option in mysql... Is that the case? Well, if it is then try changing the time to UTC or use linux timestamps. I think that would work. I think we'd have to use UNIX_TIMESTAMP (NOW ()) in the time field of the database. Could you please attach a screenshot of the time field of the database so I can understand the problem better?

**Comment by aminozuur** [comment]
I logged and I see dates for likes displayed as: 2016-12-06 01:40:32

**Comment by aminozuur** [comment]
Wait let a niqqa just DM you the login details for phpmyadmin

**Comment by candh** [comment]
seems like the dates are stored using TIMESTAMP which does some conversion on the time based on the time region set on the server. I'll take a look!
